version: '2'
services:
############################################################################
#   Emcc compiler + node js
############################################################################
  ubuntu:
    container_name: 'ubuntu'
    build:
      context: ./
      dockerfile: ./docker/ubuntu.docker
    volumes:
      - ./:/var/www
      - ./docker/scripts/build_in_container.sh:/usr/local/bin/build_in_container
      - ~/.emscripten_cache:/root/.emscripten_cache
    ports:
      - "35729:35729" # for livereload plugin
    tty: true
############################################################################
#   Nginx for run web application
############################################################################
  nginx:
    container_name: 'nginx'
    build:
      context: ./
      dockerfile: ./docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
